use super::TextKey;

pub fn get_text(key: TextKey) -> &'static str {
    match key {
        TextKey::OperationLog => "سجل العمليات",
        TextKey::Contact => ":اتصل بنا",
        TextKey::CopyTelegram => "نسخ رابط Telegram",
        TextKey::CopyWeChat => "نسخ معرف WeChat",
        TextKey::CopyDiscord => "نسخ معرف Discord",
        TextKey::TelegramLink => "رابط Telegram",
        TextKey::WeChatID => "معرف WeChat",
        TextKey::DiscordID => "معرف Discord",
        TextKey::Copied => ":تم النسخ\n{}",
        TextKey::CheckingFiles => "...جارٍ فحص الملفات",
        TextKey::MissingFiles => "ملفات مفقودة",
        TextKey::FileCheckSuccess => "!تم التحقق من جميع الملفات بنجاح",
        TextKey::SystemCheck => "فحص النظام",
        TextKey::WelcomeMessage => "{} مرحبًا بك في أداة",
        TextKey::CheckingItem => "{}:جارٍ الفحص",
        TextKey::CountdownMessage => "...{} ثانية{}سيتم المتابعة تلقائيًا في ",
        TextKey::ExitButton => "خروج",
        TextKey::MissingFilesWarning => "تحذير: قد يتسبب المتابعة بدون الملفات المطلوبة في حدوث أخطاء",
        TextKey::GroupExecutables => "الملفات التنفيذية",
        TextKey::GroupLibraries => "المكتبات",
        TextKey::GroupBitstreams => "Bitstreams",
        TextKey::GroupConfigs => "ملفات التكوين",
        TextKey::GroupOther => "ملفات أخرى",
        TextKey::ContinueAnyway => "المتابعة على أي حال",
        TextKey::Rescan => "فحص الملفات مرة أخرى",
        TextKey::SelectOperation => "اختر العملية",
        TextKey::FlashFirmware => "فلاش البرنامج الثابت",
        TextKey::ReadDna => "قراءة DNA للوحة",
        TextKey::SelectFirmware => "اختر ملف البرنامج الثابت",
        TextKey::ScanningFirmware => "...جارٍ البحث عن ملفات البرنامج الثابت",
        TextKey::SelectOption => "اختر الخيار",
        TextKey::Flash => "فلاش",
        TextKey::Read => "قراءة",
        TextKey::Back => "رجوع",
        TextKey::FlashingInProgress => "...جارٍ الفلاش",
        TextKey::ReadingDnaInProgress => "...جارٍ قراءة DNA",
        TextKey::Success => "!نجحت العملية",
        TextKey::Failed => "!فشلت العملية",
        TextKey::TryAgain => "حاول مرة أخرى",
        TextKey::ReturnToMenu => "العودة إلى القائمة",
        TextKey::DownloadHere => "تحميل من هنا",
        TextKey::UpdateAvailable => "تحديث متاح",
        TextKey::NoFirmwareFound => "لم يتم العثور على ملفات برنامج ثابت في الدليل الحالي",
        TextKey::PlaceFirmwareHere => ".bin يرجى وضع ملفات البرنامج الثابت في دليل التطبيق",
        TextKey::AutoScanning => "فحص تلقائي كل 3 ثوانٍ",
        TextKey::AutoRefreshing => "تحديث تلقائي",
        TextKey::PerformCleanup => "تنفيذ التنظيف",
        TextKey::CleanupDescription => "(.bin حذف ملف الهدف إذا نجح الفلاش)",
        TextKey::Continue => "متابعة",
        TextKey::SelectFirmwareToContinue => "اختر ملف برنامج ثابت للمتابعة",
        TextKey::FlashFirmwareDesc => "تحميل البرنامج الثابت على جهازك",
        TextKey::ReadDnaDesc => "استرداد المعرف الفريد من جهازك",
        TextKey::SelectFlashingOption => "اختر خيار الفلاش",
        TextKey::SelectDnaReadOption => "DNA اختر خيار قراءة",
        TextKey::Ch347Options => "CH347 خيارات",
        TextKey::Rs232Options => "RS232 خيارات",
        
        TextKey::Ch347_35T_Label => "CH347 - 35T",
        TextKey::Ch347_35T_Desc => "CH347 باستخدام واجهة 35T للوحات",
        TextKey::Ch347_75T_Label => "CH347 - 75T",
        TextKey::Ch347_75T_Desc => "CH347 باستخدام واجهة 75T للوحات",
        TextKey::Ch347_100T_Label => "CH347 - 100T",
        TextKey::Ch347_100T_Desc => "CH347 باستخدام واجهة 100T للوحات",

        TextKey::Rs232_35T_Label => "RS232 - 35T",
        TextKey::Rs232_35T_Desc => "RS232 باستخدام واجهة 35T للوحات",
        TextKey::Rs232_75T_Label => "RS232 - 75T",
        TextKey::Rs232_75T_Desc => "RS232 باستخدام واجهة 75T للوحات",
        TextKey::Rs232_100T_Label => "RS232 - 100T",
        TextKey::Rs232_100T_Desc => "RS232 باستخدام واجهة 100T للوحات",

        TextKey::Dna_Ch347_Label => "CH347 - DNA :100T ،75T ،35T :قراءة",
        TextKey::Dna_Ch347_Desc => "CH347 باستخدام واجهة 100T أو 75T أو 35T من DNA قراءة",
        TextKey::Dna_Rs232_35T_Label => "RS232 - DNA :35T :قراءة",
        TextKey::Dna_Rs232_35T_Desc => "RS232 باستخدام واجهة 35T من لوحات DNA قراءة",
        TextKey::Dna_Rs232_75T_Label => "RS232 - DNA :75T :قراءة",
        TextKey::Dna_Rs232_75T_Desc => "RS232 باستخدام واجهة 75T من لوحات DNA قراءة",
        TextKey::Dna_Rs232_100T_Label => "RS232 - DNA :100T :قراءة",
        TextKey::Dna_Rs232_100T_Desc => "RS232 باستخدام واجهة 100T من لوحات DNA قراءة",
        
        TextKey::ClearLog => "مسح السجل",
        
        TextKey::OperationTook => "استغرقت العملية",
        TextKey::NoteFewerSectors => ".ملاحظة: تم إتمام العملية بأقل من 10 قطاعات. يرجى التحقق يدويًا أو المحاولة مرة أخرى",
        TextKey::NoteVerifySuccess => ".ملاحظة: لم يتمكن من التحقق من النجاح الكامل، ولكن لم يتم الكشف عن أخطاء. يرجى التحقق يدويًا أو المحاولة مرة أخرى",
        TextKey::ErrorDetails => "تفاصيل الخطأ",

        TextKey::Initializing => "...جارٍ التهيئة",
        TextKey::StartingOperation => "...جارٍ بدء العملية",
        TextKey::WritingImage => "...flash جارٍ كتابة الصورة في ذاكرة",
        TextKey::ProbingFlash => "...flash جارٍ فحص ذاكرة",
        TextKey::ResettingFpga => "...FPGA جارٍ إعادة تعيين وإيقاف",
        TextKey::LoadingBitstream => "...bitstream جارٍ تحميل",
        TextKey::InitJtag => "...JTAG جارٍ تهيئة واجهة",
        TextKey::Verifying => "...جارٍ الاختبار والتحقق",
        TextKey::WritingSector => "جارٍ كتابة القطاع",
        TextKey::ReadingDeviceDna => "DNA جارٍ قراءة",
        TextKey::PleaseWaitDna => ".يرجى الانتظار بينما نسترجع المعرف الفريد من جهازك",
        TextKey::DnaTakesSeconds => ".عادةً ما تستغرق هذه العملية بضع ثوانٍ",
        TextKey::FlashingFirmware => "فلاش البرنامج الثابت",
        TextKey::PleaseWaitFlash => ".يرجى الانتظار بينما يتم كتابة البرنامج الثابت على جهازك",
        TextKey::FlashTakesMinutes => ".عادة ما تستغرق هذه العملية 1-2 دقيقة",
        TextKey::FlashFailImmediate => ".إذا اكتملت العملية على الفور، فمن المحتمل أن تكون قد فشلت",
        TextKey::TechnicalInfo => "معلومات تقنية",
        TextKey::InterfaceLabel => ":الواجهة",
        TextKey::OperationTypeLabel => ":نوع العملية",
        TextKey::TargetDeviceLabel => ":الجهاز المستهدف",
        
        TextKey::DnaReadSuccess => "!DNA نجحت قراءة",
        TextKey::DnaReadFailed => "DNA فشلت قراءة",
        TextKey::DnaReadUnexpected => "DNA حالة غير متوقعة لقراءة",
        TextKey::DeviceDnaHeader => "DNA الجهاز",
        TextKey::ClickToCopy => "انقر للنسخ",
        TextKey::FlashingSuccess => "!نجح الفلاش",
        TextKey::FlashingFailed => "فشل الفلاش",
        TextKey::FlashingFailedConnection => "فشل الفلاش - مشكلة في الاتصال",
        TextKey::FlashingResultUnknown => "نتيجة الفلاش غير معروفة",
        TextKey::NextSteps => "الخطوات التالية",
        TextKey::NextStepsList => "\\n1. إعادة تشغيل كلا الكمبيوترين\\n2. اتبع الخطوات التالية في الدليل\\n   - تثبيت برنامج تشغيل البرنامج الثابت على كمبيوتر المضيف\\n   DATA ستبدل الكابل إلى منفذ - \\n   تنشيط باستخدام البرنامج المقدم ورمز التنشيط -\\n   DNA لا تتطلب إصدارات البرنامج الثابت المقفلة بواسطة تنشيطًا -",
        TextKey::Exit => "خروج",
        TextKey::MainMenu => "القائمة الرئيسية",
        TextKey::TryAgainButton => "حاول مرة أخرى",
        
        TextKey::DnaReadUnexpectedMsg => ".DNA\\nقد يشير هذا إلى مشكلة في عملية استخراج .DNA اكتملت العملية، ولكن لم يكن من الممكن تأكيد قيمة\\n.يرجى التحقق من مخرجات السجل للحصول على التفاصيل",
        TextKey::DnaReadFailedPrefix => ":DNA من الجهاز DNA فشل في قراءة",
        TextKey::OperationInProgress => ":جارٍ االعملية",
        TextKey::DnaStatusUnknownMsg => ".DNA\\nيرجى التحقق من السجل للحصول على التفاصيل .حالة عملية قراءة غير معروفة",
        TextKey::ClickToCopyTooltip => "Verilog و HEX و RAW قيم DNA انقر لنسخ",
        TextKey::FlashingFailedConnectionMsg => "\\n.{} من {} :الكتابات العاديةغير كافية للقطاعات\\n\\nهذا يشير إلى مشكلة في اتصال الأجهزة. الجهاز قابل للوصول، ولكن البيانات لا\\n.يتم نقلها بشكل صحيح\\n\\n:جرب\\n1. استخدام منفذ USB مختلف\\n2. التحقق من توصيلات الكابل\\n3. التأكد من أن الجهاز يعمل بالطاقة بشكل صحيح\\n4. تجربة كابل USB مختلف",
        TextKey::FlashingResultUnknownMsg => ".\\n\\n اكتملت عملية الفلاش، ولكن لم يتم العثور على معلومات كتابة القطاع في السجلات\\n\\n1. قمت بتحديد نوع اللوحة الصحيح\\n JTAG مثبت وفي منفذ USB برنامج تشغيل 2. ال\\n USB مختلف و/أو منفذ USB 3. جرب كابل\\n.PCIE 4. تأكد من أن الجهاز متموضع بشكل صحيح في فتحة",
        TextKey::UnexpectedStateMsg => ".لا ينبغي الوصول إلى هذه الحالة. يرجى الإبلاغ عن هذا الخطأ",
        TextKey::FlashingFailedPrefix => ":فشل في فلاش البرنامج الثابت على الجهاز",
        TextKey::FlashStatusUnknownMsg => ".حالة عملية الفلاش غير معروفة\\n.يرجى التحقق من السجل للحصول على التفاصيل أو المحاولة مرة أخرى",

        TextKey::DnaInvalidOption => "DNA خيار غير صالح لقراءة",
        TextKey::DnaCommandFailed => "DNA فشل في تنفيذ أمر قراءة",
        TextKey::DnaFileNotFound => "{} بعد DNA لم يتم العثور على ملف إخراج محاولات",
        TextKey::DnaExtractFailed => "{}:DNA فشل في استخراج",
        TextKey::DnaFileReadError => "{}:{} في DNA فشل في قراءة ملف إخراج",
        TextKey::DnaInfoNotFound => "في ملف الإخراج DNA فشل في العثور على معلومات",
        TextKey::DnaWaitingStart => "...DNA انتظار بدء قراءة",
        TextKey::DnaRetrieving => "...DNA استرداد",
        TextKey::DnaReadSuccessStatus => "!DNA نجحت قراءة",
        TextKey::DnaOperationCompleted => "(DNA اكتملت العملية (غير",
        TextKey::DnaReadFailedStatus => "{}:DNA فشلت قراءة",
    }
}
