use super::TextKey;

pub fn get_text(key: TextKey) -> &'static str {
    match key {
        TextKey::OperationLog => "Operation Log",
        TextKey::Contact => "Contact:",
        TextKey::CopyTelegram => "Copy Telegram Link",
        TextKey::CopyWeChat => "Copy WeChat ID",
        TextKey::CopyDiscord => "Copy Discord ID",
        TextKey::TelegramLink => "Telegram Link",
        TextKey::WeChatID => "WeChat ID",
        TextKey::DiscordID => "Discord ID",
        TextKey::Copied => "Copied:\n{}",
        TextKey::CheckingFiles => "Checking Files...",
        TextKey::MissingFiles => "Missing Files",
        TextKey::FileCheckSuccess => "All files validated successfully!",
        TextKey::SystemCheck => "System Check",
        TextKey::WelcomeMessage => "Welcome to the {} Tool",
        TextKey::CheckingItem => "Checking: {}",
        TextKey::CountdownMessage => "Continuing automatically in {} second{}...",
        TextKey::ExitButton => "Exit",
        TextKey::MissingFilesWarning => "WARNING: Continuing without required files may cause errors",
        TextKey::GroupExecutables => "Executables",
        TextKey::GroupLibraries => "Libraries",
        TextKey::GroupBitstreams => "Bitstreams",
        TextKey::GroupConfigs => "Configuration Files",
        TextKey::GroupOther => "Other Files",
        TextKey::ContinueAnyway => "Continue Anyway",
        TextKey::Rescan => "Rescan Files",
        TextKey::SelectOperation => "Select Operation",
        TextKey::FlashFirmware => "Flash Firmware",
        TextKey::ReadDna => "Read Box DNA",
        TextKey::SelectFirmware => "Select Firmware File",
        TextKey::ScanningFirmware => "Scanning for firmware files...",
        TextKey::SelectOption => "Select Option",
        TextKey::Flash => "Flash",
        TextKey::Read => "Read",
        TextKey::Back => "Back",
        TextKey::FlashingInProgress => "Flashing in Progress...",
        TextKey::ReadingDnaInProgress => "Reading DNA in Progress...",
        TextKey::Success => "Operation Successful!",
        TextKey::Failed => "Operation Failed!",
        TextKey::TryAgain => "Try Again",
        TextKey::ReturnToMenu => "Return to Menu",
        TextKey::DownloadHere => "Download Here",
        TextKey::UpdateAvailable => "Update Available",
        // Firmware Selection
        TextKey::NoFirmwareFound => "No firmware files found in current directory",
        TextKey::PlaceFirmwareHere => "Please place .bin firmware files in the application directory",
        TextKey::AutoScanning => "Auto-scanning every 3 seconds",
        TextKey::AutoRefreshing => "Auto-refreshing",
        TextKey::PerformCleanup => "Perform Clean up",
        TextKey::CleanupDescription => "(Delete target .bin file if flash successful)",
        TextKey::Continue => "Continue",
        TextKey::SelectFirmwareToContinue => "Select a firmware file to continue",
        TextKey::FlashFirmwareDesc => "Upload firmware to your device",
        TextKey::ReadDnaDesc => "Retrieve the unique ID from your device",
        // Flashing Options
        TextKey::SelectFlashingOption => "Select Flashing Option",
        TextKey::SelectDnaReadOption => "Select DNA Read Option",
        TextKey::Ch347Options => "CH347 Options",
        TextKey::Rs232Options => "RS232 Options",
        
        TextKey::Ch347_35T_Label => "CH347 - 35T",
        TextKey::Ch347_35T_Desc => "For 35T boards using CH347 interface",
        TextKey::Ch347_75T_Label => "CH347 - 75T",
        TextKey::Ch347_75T_Desc => "For 75T boards using CH347 interface",
        TextKey::Ch347_100T_Label => "CH347 - 100T",
        TextKey::Ch347_100T_Desc => "For 100T boards using CH347 interface",

        TextKey::Rs232_35T_Label => "RS232 - 35T",
        TextKey::Rs232_35T_Desc => "For 35T boards using RS232 interface",
        TextKey::Rs232_75T_Label => "RS232 - 75T",
        TextKey::Rs232_75T_Desc => "For 75T boards using RS232 interface",
        TextKey::Rs232_100T_Label => "RS232 - 100T",
        TextKey::Rs232_100T_Desc => "For 100T boards using RS232 interface",

        TextKey::Dna_Ch347_Label => "CH347 - DNA Read: 35T, 75T, 100T",
        TextKey::Dna_Ch347_Desc => "Read DNA from 35T, 75T, or 100T using CH347 interface",
        TextKey::Dna_Rs232_35T_Label => "RS232 - DNA Read: 35T",
        TextKey::Dna_Rs232_35T_Desc => "Read DNA from 35T boards using RS232 interface",
        TextKey::Dna_Rs232_75T_Label => "RS232 - DNA Read: 75T",
        TextKey::Dna_Rs232_75T_Desc => "Read DNA from 75T boards using RS232 interface",
        TextKey::Dna_Rs232_100T_Label => "RS232 - DNA Read: 100T",
        TextKey::Dna_Rs232_100T_Desc => "Read DNA from 100T boards using RS232 interface",
        
        // Log View
        TextKey::ClearLog => "Clear Log",
        
        // Result Extras
        TextKey::OperationTook => "Operation took",
        TextKey::NoteFewerSectors => "Note: Operation completed with fewer than 10 sectors. Please verify manually or try again.",
        TextKey::NoteVerifySuccess => "Note: Unable to verify complete success, but no errors were detected. Please verify manually or try again.",
        TextKey::ErrorDetails => "Error Details",

        // Progress
        TextKey::Initializing => "Initializing...",
        TextKey::StartingOperation => "Starting operation...",
        TextKey::WritingImage => "Writing image to flash memory...",
        TextKey::ProbingFlash => "Probing flash memory...",
        TextKey::ResettingFpga => "Resetting and halting FPGA...",
        TextKey::LoadingBitstream => "Loading bitstream...",
        TextKey::InitJtag => "Initializing JTAG interface...",
        TextKey::Verifying => "Testing and verifying...",
        TextKey::WritingSector => "Writing sector",
        TextKey::ReadingDeviceDna => "Reading Device DNA",
        TextKey::PleaseWaitDna => "Please wait while we retrieve the unique ID from your device.",
        TextKey::DnaTakesSeconds => "This typically takes a few seconds to complete.",
        TextKey::FlashingFirmware => "Flashing Firmware",
        TextKey::PleaseWaitFlash => "Please wait while the firmware is being written to your device.",
        TextKey::FlashTakesMinutes => "This typically takes 1-2 minutes to complete.",
        TextKey::FlashFailImmediate => "If the process completes immediately, it likely failed.",
        TextKey::TechnicalInfo => "Technical Information",
        TextKey::InterfaceLabel => "Interface:",
        TextKey::OperationTypeLabel => "Operation Type:",
        TextKey::TargetDeviceLabel => "Target Device:",
        
        // Result
        TextKey::DnaReadSuccess => "DNA READ SUCCESSFUL!",
        TextKey::DnaReadFailed => "DNA READ FAILED",
        TextKey::DnaReadUnexpected => "DNA READ STATUS UNEXPECTED",
        TextKey::DeviceDnaHeader => "Device DNA",
        TextKey::ClickToCopy => "Click to copy",
        TextKey::FlashingSuccess => "FLASHING SUCCESSFUL!",
        TextKey::FlashingFailed => "FLASHING FAILED",
        TextKey::FlashingFailedConnection => "FLASHING FAILED - CONNECTION ISSUE",
        TextKey::FlashingResultUnknown => "FLASHING RESULT UNKNOWN",
        TextKey::NextSteps => "Next Steps",
        TextKey::NextStepsList => "1. Reboot both computers\n2. Follow the next steps in the guide\n   - Install firmware driver on host computer\n   - Swap cable to DATA port\n   - Activate using provided software and activation code\n   - DNA locked firmware builds do not require activation",
        TextKey::Exit => "Exit",
        TextKey::MainMenu => "Main Menu",
        TextKey::TryAgainButton => "Try Again",
        
        // Detailed Result Messages
        TextKey::DnaReadUnexpectedMsg => "The operation completed, but the DNA value could not be confirmed.\nThis might indicate an issue with the DNA extraction process.\nPlease check the log output for details.",
        TextKey::DnaReadFailedPrefix => "Failed to read DNA from the device:",
        TextKey::OperationInProgress => "Operation in progress:",
        TextKey::DnaStatusUnknownMsg => "DNA read operation status is unknown.\nPlease check the log for details.",
        TextKey::ClickToCopyTooltip => "Click to copy RAW, HEX, and Verilog DNA values",
        TextKey::FlashingFailedConnectionMsg => "Insufficient normal sector writes detected: {} out of {} sectors.\n\nThis indicates a hardware connection issue. The device is accessible but data is not being properly transferred.\n\nTry:\n1. Use a different USB port\n2. Check cable connections\n3. Ensure the device is powered correctly\n4. Try a different USB cable",
        TextKey::FlashingResultUnknownMsg => "Flashing process completed but no sector write information was found in logs.\n\n1. You selected the correct board type\n2. The appropriate USB driver is installed and in JTAG port.\n3. Try a different USB cable and/or port\n4. Make sure the device is properly seated in the PCIE slot.",
        TextKey::UnexpectedStateMsg => "This state should not be reached. Please report this bug.",
        TextKey::FlashingFailedPrefix => "Failed to flash firmware to the device:",
        TextKey::FlashStatusUnknownMsg => "Flash operation status is unknown.\nPlease check the log for details or try again.",

        // DNA Backend & Status
        TextKey::DnaInvalidOption => "Invalid option for DNA read",
        TextKey::DnaCommandFailed => "Failed to execute DNA read command",
        TextKey::DnaFileNotFound => "DNA output file not found after {} attempts",
        TextKey::DnaExtractFailed => "Failed to extract DNA: {}",
        TextKey::DnaFileReadError => "Failed to read DNA output file at {}: {}",
        TextKey::DnaInfoNotFound => "Could not find DNA information in the output file",
        TextKey::DnaWaitingStart => "Waiting to start DNA read...",
        TextKey::DnaRetrieving => "Retrieving device DNA...",
        TextKey::DnaReadSuccessStatus => "DNA read successful!",
        TextKey::DnaOperationCompleted => "Operation completed (Non-DNA)",
        TextKey::DnaReadFailedStatus => "DNA read failed: {}",
    }
}
